export interface PreventivePlanItem {
  id: string;
  num: number | string;
  prio: 'ALTO' | 'MEDIO';
  actividad: string;
  ubicacion: string;
  frecuencia: string;
  presupuesto_proyectado: number;
  responsable: string;
  fecha_tdr_revision: string;
  fecha_tdr_envio: string;
  rq: string;
  acuerdo: string;
  proveedor: string;
  monto_sin_igv: number;
  estado_original: string;
  active_weeks: number[];
  assigned_staff_id: string | null;
  assigned_contractor?: string;
  status: 'Pendiente' | 'Realizado';
  budgetItemLinkId?: string; // Links to Capex or Opex item key
  budgetItemLinkType?: 'CAPEX' | 'OPEX';
  completed_weeks?: number[]; // Weeks that have been completed
}

export const MOCK_PREVENTIVE_PLAN: PreventivePlanItem[] = [
  {
    "id": "pm-A",
    "num": "A",
    "prio": "MEDIO",
    "actividad": "CALDEROS, ABLANDADORES Y CALENTADORES",
    "ubicacion": "",
    "frecuencia": "",
    "presupuesto_proyectado": 134500,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-1",
    "num": 1,
    "prio": "ALTO",
    "actividad": "CALDERO ACUOTUBULAR APIN 150 HP",
    "ubicacion": "PISCINA OLMPICA",
    "frecuencia": "SEMESTRAL",
    "presupuesto_proyectado": 17000,
    "responsable": "WILIAM ANTICONA",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "480701179",
    "acuerdo": "APROBADO\nACTA N°004-26",
    "proveedor": "CALDERAS INGENIERIA Y\r\nSERVICIOS GENERALES S.A.C.,",
    "monto_sin_igv": 16960,
    "estado_original": "EN COORDINACIÓN PARA SU EJECUCIÓN",
    "active_weeks": [
      13,
      17,
      25
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-2",
    "num": 2,
    "prio": "ALTO",
    "actividad": "INTERCAMBIADOR CALOR DE PLACAS ALFA LAVAL N°1",
    "ubicacion": "PISCINA OLMPICA",
    "frecuencia": "SEMESTRAL",
    "presupuesto_proyectado": 6000,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      13,
      17,
      21
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-3",
    "num": 3,
    "prio": "ALTO",
    "actividad": "INTERCAMBIADOR CALOR DE PLACAS ALFA LAVAL N°2",
    "ubicacion": "PISCINA OLMPICA",
    "frecuencia": "SEMESTRAL",
    "presupuesto_proyectado": 6000,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      13,
      17,
      21
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-4",
    "num": 4,
    "prio": "ALTO",
    "actividad": "CALENTADOR MERCURY BOILER",
    "ubicacion": "PISCINA TECHADA",
    "frecuencia": "SEMESTRAL",
    "presupuesto_proyectado": 9900,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      13,
      17,
      23
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-5",
    "num": 5,
    "prio": "ALTO",
    "actividad": "FLTRO MULTIMEDIA Y ABLANDADORES TWIN 15 PIES3",
    "ubicacion": "PISCINA OLMPICA",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 15000,
    "responsable": "WILIAM ANTICONA",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "480701356",
    "acuerdo": "APROBADO\nACTA N°004-26",
    "proveedor": "SERVICE WATER TREATMENT\r\nS.A.C.,",
    "monto_sin_igv": 18100,
    "estado_original": "EN COORDINACIÓN PARA SU EJECUCIÓN",
    "active_weeks": [
      13,
      17,
      25
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-6",
    "num": 6,
    "prio": "ALTO",
    "actividad": "ABLANDADORES TWIN 5",
    "ubicacion": "BAÑOS TURCOS",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 22000,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      13,
      17,
      25
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-7",
    "num": 7,
    "prio": "ALTO",
    "actividad": "CALDERO VERTICAL JYR 40HP N°1",
    "ubicacion": "BAÑOS TURCOS",
    "frecuencia": "SEMESTRAL",
    "presupuesto_proyectado": 10400,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      13,
      17,
      21
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-8",
    "num": 8,
    "prio": "ALTO",
    "actividad": "CALDERO VERTICAL JYR 40HP N°2",
    "ubicacion": "BAÑOS TURCOS",
    "frecuencia": "SEMESTRAL",
    "presupuesto_proyectado": 10400,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      13,
      17,
      25
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-9",
    "num": 9,
    "prio": "ALTO",
    "actividad": "CALENTADOR PIROTUBULAR VERTIAL JYR  750 GLN  N° 1",
    "ubicacion": "BAÑOS TURCOS",
    "frecuencia": "SEMESTRAL",
    "presupuesto_proyectado": 9900,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      13,
      17,
      25
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-10",
    "num": 10,
    "prio": "ALTO",
    "actividad": "CALENTADOR PIROTUBULAR VERTIAL JYR  750 GLN  N° 2",
    "ubicacion": "BAÑOS TURCOS",
    "frecuencia": "SEMESTRAL",
    "presupuesto_proyectado": 9900,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      13,
      17,
      25
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-11",
    "num": 11,
    "prio": "ALTO",
    "actividad": "MANTENIMIENTO DE FILTROS",
    "ubicacion": "BAÑOS TURCOS",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 18000,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-B",
    "num": "B",
    "prio": "MEDIO",
    "actividad": "ELECTROBOMBAS",
    "ubicacion": "",
    "frecuencia": "",
    "presupuesto_proyectado": 135292,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-1",
    "num": 1,
    "prio": "ALTO",
    "actividad": "ELECTROBOMBA 50 HP N° 1",
    "ubicacion": "POZO SEPTICO PRINCIPAL",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 17670,
    "responsable": "MARLON RIVERA",
    "fecha_tdr_revision": "46172",
    "fecha_tdr_envio": "46159",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "- TDR ENVIADO AL ÁREA DE LOGÍSTICA.\n- PENDIENTE DE PROGRAMACIÓN DE VISITA CON LOS CONTRATISTAS.",
    "active_weeks": [
      25,
      28
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-2",
    "num": 2,
    "prio": "ALTO",
    "actividad": "ELECTROBOMBA 50 HP N° 2",
    "ubicacion": "POZO SEPTICO PRINCIPAL",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 17670,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      47
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-3",
    "num": 3,
    "prio": "ALTO",
    "actividad": "BOMBAS SUMERGIBLES  25 HP N° 1",
    "ubicacion": "POZO SEPTICO PRINCIPAL",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 9690,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      14,
      42
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-4",
    "num": 4,
    "prio": "ALTO",
    "actividad": "BOMBAS SUMERGIBLES  25 HP N° 2",
    "ubicacion": "POZO SEPTICO PRINCIPAL",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 9690,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      36
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-5",
    "num": 5,
    "prio": "ALTO",
    "actividad": "ELECTROBOMBAS HIDROSTAL 5.7 HP N° 1",
    "ubicacion": "RESERVORIO PRINCIPAL",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 2560,
    "responsable": "WILIAM ANTICONA",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      28
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-6",
    "num": 6,
    "prio": "ALTO",
    "actividad": "ELECTROBOMBAS HIDROSTAL 5.7 HP N° 2",
    "ubicacion": "RESERVORIO PRINCIPAL",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 2560,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      28
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-7",
    "num": 7,
    "prio": "ALTO",
    "actividad": "ELECTROBOMBAS HIDROSTAL 5.7 HP N° 3",
    "ubicacion": "RESERVORIO PRINCIPAL",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 2560,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      28
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-8",
    "num": 8,
    "prio": "ALTO",
    "actividad": "ELECTROBOMBAS  20 HP N° 1",
    "ubicacion": "PISCINA OLIMPICA",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 3346,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      31
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-9",
    "num": 9,
    "prio": "ALTO",
    "actividad": "ELECTROBOMBAS  20 HP N° 2",
    "ubicacion": "PISCINA OLIMPICA",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 3346,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      32
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-10",
    "num": 10,
    "prio": "ALTO",
    "actividad": "ELECTROBOMBAS  2.5 HP N° 1",
    "ubicacion": "PISCINA TECHADA",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 1350,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      36
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-11",
    "num": 11,
    "prio": "ALTO",
    "actividad": "ELECTROBOMBAS  2.5 HP N° 2",
    "ubicacion": "PISCINA TECHADA",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 1350,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      36
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-12",
    "num": 12,
    "prio": "ALTO",
    "actividad": "ELECTROBOMBAS  2.5 HP N° 3",
    "ubicacion": "PISCINA TECHADA",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 1350,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      36
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-13",
    "num": 13,
    "prio": "ALTO",
    "actividad": "ELECTROBOMBAS  2.5 HP N° 4",
    "ubicacion": "PISCINA TECHADA",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 1350,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      36
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-14",
    "num": 14,
    "prio": "ALTO",
    "actividad": "BOMBA SUMERGIBLE 5HP N° 1",
    "ubicacion": "20 KM",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 2560,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      36
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-15",
    "num": 15,
    "prio": "ALTO",
    "actividad": "BOMBA SUMERGIBLE 5HP N° 2",
    "ubicacion": "20 KM",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 2560,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      36
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-16",
    "num": 16,
    "prio": "ALTO",
    "actividad": "BOMBA SUMERGIBLE 3HP N° 1",
    "ubicacion": "FOOD COURT",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 2560,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      38
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-17",
    "num": 17,
    "prio": "ALTO",
    "actividad": "BOMBA SUMERGIBLE 3HP N° 1",
    "ubicacion": "ZSA ZSA",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 2560,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      38
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-18",
    "num": 18,
    "prio": "ALTO",
    "actividad": "BOMBA SUMERGIBLE 3HP N° 1",
    "ubicacion": "PLAYA 3",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 2560,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      38
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-19",
    "num": 19,
    "prio": "ALTO",
    "actividad": "BOMBAS CENTRIFUGAS DE MENOR POTENCIA 40",
    "ubicacion": "CLUB",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 48000,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      38
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-C",
    "num": "C",
    "prio": "MEDIO",
    "actividad": "GRUPO ELECTROGENO",
    "ubicacion": "",
    "frecuencia": "",
    "presupuesto_proyectado": 10900,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-1",
    "num": 1,
    "prio": "ALTO",
    "actividad": "GRUPO ELECTROGENO 3406 250KVA",
    "ubicacion": "RESTAURANT REMOS",
    "frecuencia": "SEMESTRAL",
    "presupuesto_proyectado": 10900,
    "responsable": "MARLON RIVERA",
    "fecha_tdr_revision": "46134",
    "fecha_tdr_envio": "46063",
    "rq": "480703113",
    "acuerdo": "NO REQUIERE",
    "proveedor": "TPM INGENIERIA E IMPORTACIONES S.A.C.",
    "monto_sin_igv": 0,
    "estado_original": "EJECUTADO",
    "active_weeks": [
      11,
      14,
      15
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-D",
    "num": "D",
    "prio": "MEDIO",
    "actividad": "ASCENSORES",
    "ubicacion": "",
    "frecuencia": "",
    "presupuesto_proyectado": 27275.27,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-1",
    "num": 1,
    "prio": "ALTO",
    "actividad": "ASCENSOR OTIS 1625620",
    "ubicacion": "CANCHA DE TENIS",
    "frecuencia": "MENSUAL",
    "presupuesto_proyectado": 2479.57,
    "responsable": "WILIAM ANTICONA",
    "fecha_tdr_revision": "46134",
    "fecha_tdr_envio": "46165",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "- TDR ENVIADO AL ÁREA DE LOGÍSTICA.\n- PENDIENTE DE PROGRAMACIÓN DE VISITA CON LOS CONTRATISTAS.",
    "active_weeks": [
      2,
      7,
      12,
      16,
      20,
      25,
      29,
      33,
      37,
      42,
      47,
      52
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-2",
    "num": 2,
    "prio": "ALTO",
    "actividad": "ASCENSOR OTIS 1625621",
    "ubicacion": "EDIFICIO ESTACIONAMENTO",
    "frecuencia": "MENSUAL",
    "presupuesto_proyectado": 2479.57,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      2,
      7,
      12,
      16,
      20,
      25,
      29,
      33,
      37,
      42,
      47,
      52
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-3",
    "num": 3,
    "prio": "ALTO",
    "actividad": "ASCENSOR OTIS 1625622",
    "ubicacion": "EDIFICIO ESTACIONAMENTO",
    "frecuencia": "MENSUAL",
    "presupuesto_proyectado": 2479.57,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      2,
      7,
      12,
      16,
      20,
      25,
      29,
      33,
      37,
      42,
      47,
      52
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-4",
    "num": 4,
    "prio": "ALTO",
    "actividad": "ASCENSOR OTIS 1625623",
    "ubicacion": "EDIFICIO INSTITUCIONAL",
    "frecuencia": "MENSUAL",
    "presupuesto_proyectado": 2479.57,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      2,
      7,
      12,
      16,
      20,
      25,
      29,
      33,
      37,
      42,
      47,
      52
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-5",
    "num": 5,
    "prio": "ALTO",
    "actividad": "ASCENSOR OTIS 1625624",
    "ubicacion": "EDIFICIO 7 PISOS",
    "frecuencia": "MENSUAL",
    "presupuesto_proyectado": 2479.57,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      2,
      7,
      12,
      16,
      20,
      25,
      29,
      33,
      37,
      42,
      47,
      52
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-6",
    "num": 6,
    "prio": "ALTO",
    "actividad": "ASCENSOR OTIS 1625625",
    "ubicacion": "EDIFICIO 7 PISOS",
    "frecuencia": "MENSUAL",
    "presupuesto_proyectado": 2479.57,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      2,
      7,
      12,
      16,
      20,
      25,
      29,
      33,
      37,
      42,
      47,
      52
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-7",
    "num": 7,
    "prio": "ALTO",
    "actividad": "ASCENSOR OTIS 1625626",
    "ubicacion": "EDIFICIO 7 PISOS",
    "frecuencia": "MENSUAL",
    "presupuesto_proyectado": 2479.57,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      2,
      7,
      12,
      16,
      20,
      25,
      29,
      33,
      37,
      42,
      47,
      52
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-8",
    "num": 8,
    "prio": "ALTO",
    "actividad": "ASCENSOR SCHNDLER 20050542",
    "ubicacion": "REST. PARADOR",
    "frecuencia": "MENSUAL",
    "presupuesto_proyectado": 2479.57,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      2,
      7,
      12,
      16,
      20,
      25,
      29,
      33,
      37,
      42,
      47,
      52
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-9",
    "num": 9,
    "prio": "ALTO",
    "actividad": "ASCENSOR SCHNDLER 20050543",
    "ubicacion": "MODULO ADM.",
    "frecuencia": "MENSUAL",
    "presupuesto_proyectado": 2479.57,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      2,
      7,
      12,
      16,
      20,
      25,
      29,
      33,
      37,
      42,
      47,
      52
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-10",
    "num": 10,
    "prio": "ALTO",
    "actividad": "PLATAFORMA TKE 2017695",
    "ubicacion": "DAMAS SOTANO",
    "frecuencia": "MENSUAL",
    "presupuesto_proyectado": 2479.57,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      2,
      7,
      12,
      16,
      20,
      25,
      29,
      33,
      37,
      42,
      47,
      52
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-11",
    "num": 11,
    "prio": "ALTO",
    "actividad": "PLATAFORMA TKE 2017696",
    "ubicacion": "REST. REMOS",
    "frecuencia": "MENSUAL",
    "presupuesto_proyectado": 2479.57,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      2,
      7,
      12,
      16,
      20,
      25,
      29,
      33,
      37,
      42,
      47,
      52
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-E",
    "num": "E",
    "prio": "MEDIO",
    "actividad": "PINTADO EDIFICACIONES",
    "ubicacion": "",
    "frecuencia": "",
    "presupuesto_proyectado": 207600.84,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-1",
    "num": 1,
    "prio": "MEDIO",
    "actividad": "MANTENIMIENTO PINTADO COLISEO BASQUET",
    "ubicacion": "COLISEO BASQUET",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 32832,
    "responsable": "DIANA ALTAMIRANO",
    "fecha_tdr_revision": "46136",
    "fecha_tdr_envio": "46146",
    "rq": "480703354",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "- TDR ENVIADO AL ÁREA DE LOGÍSTICA\n- SE REALIZARÁ LA VISITA CON LOS CONTRATISTAS EL 28/05",
    "active_weeks": [
      35
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-2",
    "num": 2,
    "prio": "MEDIO",
    "actividad": "MANTENIMIENTO PINTADO AUDITORIO",
    "ubicacion": "AUDITORIO",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 4617,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      35
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-3",
    "num": 3,
    "prio": "MEDIO",
    "actividad": "MANTENIMIENTO PINTADO SQUASH",
    "ubicacion": "SQUASH",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 2052,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      35
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-4",
    "num": 4,
    "prio": "MEDIO",
    "actividad": "MANTENIMIENTO PINTADO PABELLON DE SERVICIOS",
    "ubicacion": "PABELLON DE SERVICIOS",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 17442,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      35
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-5",
    "num": 5,
    "prio": "MEDIO",
    "actividad": "MANTENIMIENTO PINTADO EDIFICIO INSTITUCIONAL",
    "ubicacion": "EDIFICIO INSTITUCIONAL",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 19494,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      35
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-6",
    "num": 6,
    "prio": "MEDIO",
    "actividad": "MANTENIMIENTO PINTADO MODULO ADMINISTRATIVO",
    "ubicacion": "MODULO ADMINISTRATIVO",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 28728,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      35
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-7",
    "num": 7,
    "prio": "MEDIO",
    "actividad": "MANTENIMIENTO PINTADO DE BADMINTON",
    "ubicacion": "BADMINTON",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 23474.88,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      35
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-8",
    "num": 8,
    "prio": "MEDIO",
    "actividad": "MANTENIMIENTO PINTADO DE EDIFICIO DE ESTACIONAMIENTO",
    "ubicacion": "EDIFICIO DE ESTACIONAMIENTO",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 16005.6,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      35
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-7",
    "num": 7,
    "prio": "MEDIO",
    "actividad": "MANTENIMIENTO PINTADO DE  FRONTON",
    "ubicacion": "BADMINTON",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 23474.88,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      35
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-7",
    "num": 7,
    "prio": "MEDIO",
    "actividad": "MANTENIMIENTO PINTADO COLISEO DE VOLEY",
    "ubicacion": "BADMINTON",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 23474.88,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      35
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-8",
    "num": 8,
    "prio": "MEDIO",
    "actividad": "MANTENIMIENTO PINTADO DE BOCHAS",
    "ubicacion": "EDIFICIO DE ESTACIONAMIENTO",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 16005.6,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      35
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-F",
    "num": "F",
    "prio": "MEDIO",
    "actividad": "SUBESTACIONES",
    "ubicacion": "",
    "frecuencia": "",
    "presupuesto_proyectado": 30550,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-1",
    "num": 1,
    "prio": "ALTO",
    "actividad": "SUBESTACION N° 1",
    "ubicacion": "SQUASH",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 8800,
    "responsable": "MARLON RIVERA",
    "fecha_tdr_revision": "46132",
    "fecha_tdr_envio": "",
    "rq": "480701843",
    "acuerdo": "23, AGENDA 093-26",
    "proveedor": "PROMOTORES ELECTRICOS S.A.",
    "monto_sin_igv": 0,
    "estado_original": "SE HA EJECUTADO EN LAS SUBESTACIONES 1 Y 3, SE PROGRAMA PARA QUINCENA DE JUNIO SUBESTACIONES 2 Y 4",
    "active_weeks": [
      12,
      21
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-2",
    "num": 2,
    "prio": "ALTO",
    "actividad": "SUBESTACION N° 2",
    "ubicacion": "ESCUELA DE REMO",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 7250,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      12,
      23
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-3",
    "num": 3,
    "prio": "ALTO",
    "actividad": "SUBESTACION N° 3",
    "ubicacion": "SALA BAILE",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 7250,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      12,
      21
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-4",
    "num": 4,
    "prio": "ALTO",
    "actividad": "SUBESTACION N° 4",
    "ubicacion": "MODULOS DEP ZONA 3",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 7250,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      12,
      23
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-G",
    "num": "G",
    "prio": "MEDIO",
    "actividad": "POZOS SEPTICOS",
    "ubicacion": "",
    "frecuencia": "",
    "presupuesto_proyectado": 28870,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-74",
    "num": 74,
    "prio": "ALTO",
    "actividad": "Limpieza de pozos sépticos colectores de aguas servidas de la sede Chorrillos.",
    "ubicacion": "",
    "frecuencia": "",
    "presupuesto_proyectado": 7500,
    "responsable": "MARLON RIVERA",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-1",
    "num": 1,
    "prio": "ALTO",
    "actividad": "Limpieza de 02 pozos septicos principales de 22m3 y 14m3",
    "ubicacion": "SEDE",
    "frecuencia": "SEMESTRAL",
    "presupuesto_proyectado": 8500,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "46161",
    "rq": "480703305",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "POSTOR ECOIL SAC PRESENTÓ SU PROPUESTA, FALTAN MAS PROPUESTAS PARA DESIGNAR AL POSTOR GANADOR.",
    "active_weeks": [
      8,
      9,
      27,
      40,
      41
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-2",
    "num": 2,
    "prio": "ALTO",
    "actividad": "Limpieza de 02 pozos colectores Food Curt y Terraza 2",
    "ubicacion": "SEDE",
    "frecuencia": "BIMESTRAL",
    "presupuesto_proyectado": 1440,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "480704244",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "PENDIENTE DE ATENCIÓN DE LOGÍSTICA",
    "active_weeks": [
      12,
      14,
      22,
      28,
      31,
      40,
      49
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-3",
    "num": 3,
    "prio": "ALTO",
    "actividad": "Limpieza de 04 pozos colectores Zona 3, Ovalo 20km, Zsa-Zsa y Sotano E7P",
    "ubicacion": "SEDE",
    "frecuencia": "BIMESTRAL",
    "presupuesto_proyectado": 1380,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "480704242",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "PENDIENTE DE ATENCIÓN DE LOGÍSTICA",
    "active_weeks": [
      10,
      12,
      18,
      26,
      28,
      35,
      44
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-4",
    "num": 4,
    "prio": "ALTO",
    "actividad": "Servicio de limpieza y desatoro de redes de desagüe que interconectan los pozos sépticos colectores de la Sede Chorrillos.",
    "ubicacion": "SEDE",
    "frecuencia": "TRIMESTRAL",
    "presupuesto_proyectado": 10050,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      9,
      22,
      30,
      35,
      48
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-H",
    "num": "H",
    "prio": "MEDIO",
    "actividad": "POZOS A TIERRA",
    "ubicacion": "",
    "frecuencia": "",
    "presupuesto_proyectado": 8466,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-1",
    "num": 1,
    "prio": "ALTO",
    "actividad": "Mant prev de 60 Pozos de Puesta a Tierra (10 pozos por jornada)",
    "ubicacion": "SEDE",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 8466,
    "responsable": "MARLON RIVERA",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "480700795, 480701447, 480701761, 480702561",
    "acuerdo": "NO REQUIERE",
    "proveedor": "PROYECTO SANEJ S.A.C.",
    "monto_sin_igv": 12355.82,
    "estado_original": "EJECUTADO",
    "active_weeks": [
      11,
      13,
      15,
      17,
      19,
      21
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-I",
    "num": "I",
    "prio": "MEDIO",
    "actividad": "PALMERAS",
    "ubicacion": "",
    "frecuencia": "",
    "presupuesto_proyectado": 21560,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-1",
    "num": 1,
    "prio": "ALTO",
    "actividad": "Poda de hojas de 140 palmeras tipo abanico en Estacionamiento Principal.",
    "ubicacion": "SEDE",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 15400,
    "responsable": "DIANA ALTAMIRANO",
    "fecha_tdr_revision": "46136",
    "fecha_tdr_envio": "46147",
    "rq": "480703424",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "EN RECECPCIÓN DE COTIZACIONES POR PARTE DE LOGÍSTICA",
    "active_weeks": [
      36
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-2",
    "num": 2,
    "prio": "ALTO",
    "actividad": "Poda de hojas de 28 palmeras tipo fénix en Avenida Principal y Medialuna.",
    "ubicacion": "SEDE",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 6160,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      36
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-J",
    "num": "J",
    "prio": "MEDIO",
    "actividad": "AIRE ACONDICIONADO",
    "ubicacion": "",
    "frecuencia": "",
    "presupuesto_proyectado": 32440,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-1",
    "num": 1,
    "prio": "ALTO",
    "actividad": "Mantenimiento preventivo de 102 equipos de aire acondicionado del Club",
    "ubicacion": "CLUB",
    "frecuencia": "SEMESTRAL",
    "presupuesto_proyectado": 16220,
    "responsable": "WILIM ANTICONA",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "46161",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "- TDR ENVIADO AL ÁREA DE LOGÍSTICA.\n- PENDIENTE DE PROGRAMACIÓN DE VISITA CON LOS CONTRATISTAS.",
    "active_weeks": [
      27,
      28,
      29,
      30,
      31,
      32,
      33,
      34
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-2",
    "num": 2,
    "prio": "ALTO",
    "actividad": "Mantenimiento preventivo de aire acondicionado, inyectores y extractores de Palacio del Deporte",
    "ubicacion": "CLUB",
    "frecuencia": "SEMESTRAL",
    "presupuesto_proyectado": 16220,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      27,
      28,
      29,
      30,
      31,
      32,
      33,
      34
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-K",
    "num": "K",
    "prio": "MEDIO",
    "actividad": "ANALISIS Y TRATAMIENTO BACTERIOLOGICO",
    "ubicacion": "",
    "frecuencia": "",
    "presupuesto_proyectado": 98968,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-1",
    "num": 1,
    "prio": "ALTO",
    "actividad": "ANALISIS FÍSICO QUÍMICO Y BACTERIOLÓGICO DE LAS AGUA EN PISCINAS",
    "ubicacion": "CLUB",
    "frecuencia": "MENSUAL",
    "presupuesto_proyectado": 25968,
    "responsable": "MARLON RIVERA",
    "fecha_tdr_revision": "46157",
    "fecha_tdr_envio": "",
    "rq": "480700127",
    "acuerdo": "",
    "proveedor": "CERTIFICACIONES Y CALIDAD SOCIEDAD ANONIMA CERRADA",
    "monto_sin_igv": 31824,
    "estado_original": "EJECUTADO",
    "active_weeks": [
      2,
      7,
      12,
      16,
      20,
      25,
      29,
      33,
      37,
      42,
      47,
      52
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-2",
    "num": 2,
    "prio": "ALTO",
    "actividad": "TRATAMIENTO MICROBIOLÓGICO DE TRAMPAS DE GRASA Y POZO SÉPTICO",
    "ubicacion": "CLUB",
    "frecuencia": "MENSUAL",
    "presupuesto_proyectado": 73000,
    "responsable": "DIANA ALTAMIRANO",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "46058",
    "rq": "480700971",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "ACTUALIZACIÓN DE COTIZACIONES",
    "active_weeks": [
      2,
      7,
      12,
      16,
      20,
      25,
      29,
      33,
      37,
      42,
      47,
      52
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-3",
    "num": 3,
    "prio": "ALTO",
    "actividad": "ANALISIS DE AGUAS RESIDUALES",
    "ubicacion": "CLUB",
    "frecuencia": "TRIMESTRAL",
    "presupuesto_proyectado": 0,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      12,
      25,
      37,
      52
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-L",
    "num": "L",
    "prio": "MEDIO",
    "actividad": "TERMOCALENTADORES",
    "ubicacion": "",
    "frecuencia": "",
    "presupuesto_proyectado": 20000,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-1",
    "num": 1,
    "prio": "ALTO",
    "actividad": "Mantenimiento preventivo de 27 termocalentadores",
    "ubicacion": "CLUB",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 20000,
    "responsable": "WILIAM ANTICONA",
    "fecha_tdr_revision": "46157",
    "fecha_tdr_envio": "",
    "rq": "480701900",
    "acuerdo": "APROBADO\nACTA N°005-26",
    "proveedor": "CALDERAS INGENIERIA Y SERVICIOS GENERALES SAC",
    "monto_sin_igv": 27954.2,
    "estado_original": "EN COORDINACIÓN PARA SU EJECUCIÓN",
    "active_weeks": [
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      26,
      27,
      28,
      29
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-M",
    "num": "M",
    "prio": "MEDIO",
    "actividad": "SISTEMA DACI",
    "ubicacion": "",
    "frecuencia": "",
    "presupuesto_proyectado": 60000,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-1",
    "num": 1,
    "prio": "ALTO",
    "actividad": "Mantenimiento preventivo panel central de seguridad y sistema de alerta.",
    "ubicacion": "CLUB",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 60000,
    "responsable": "MARLON RIVERA / LEOMAR HUARACA",
    "fecha_tdr_revision": "46167",
    "fecha_tdr_envio": "46169",
    "rq": "480703931",
    "acuerdo": "POR APROBAR\nAGENDA N°008-26",
    "proveedor": "SHULLER SERVICE CONTRATISTAS GENERALES S.A.C.",
    "monto_sin_igv": 41241,
    "estado_original": "PENDIENTE DE APROBACIÓN EN EL CD",
    "active_weeks": [
      6,
      7,
      8,
      9,
      27,
      28,
      29,
      30
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-1",
    "num": 1,
    "prio": "ALTO",
    "actividad": "Mantenimiento preventivo cuarto de maquinas y gabinetes",
    "ubicacion": "CLUB",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 12000,
    "responsable": "",
    "fecha_tdr_revision": "46142",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      8,
      9,
      29,
      30
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-N",
    "num": "N",
    "prio": "MEDIO",
    "actividad": "SISTEMAS HIDRONEUMATICOS",
    "ubicacion": "",
    "frecuencia": "",
    "presupuesto_proyectado": 22000,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-1",
    "num": 1,
    "prio": "ALTO",
    "actividad": "Mantenimiento preventivo de 14 tanques hidroneumaticos",
    "ubicacion": "CLUB",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 22000,
    "responsable": "WILIAM ANTICONA",
    "fecha_tdr_revision": "46157",
    "fecha_tdr_envio": "46168",
    "rq": "480704144",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "EN LOGISTICA, PARA PROGRAMAR LAS VISITAS DE CAMPO.",
    "active_weeks": [
      18,
      28
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-Ñ",
    "num": "Ñ",
    "prio": "MEDIO",
    "actividad": "SISTEMAS EXTRACTOR E INYECCION DE AIRE",
    "ubicacion": "",
    "frecuencia": "",
    "presupuesto_proyectado": 25000,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-1",
    "num": 1,
    "prio": "ALTO",
    "actividad": "Mantenimiento preventivo de 42 extractores",
    "ubicacion": "CLUB",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 25000,
    "responsable": "WILIAM ANTICONA",
    "fecha_tdr_revision": "46142",
    "fecha_tdr_envio": "46069",
    "rq": "480701240",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "PENDIENTE DE REMISIÓN DE COTIZACIONES POR PARTE DE LOGÍSTICA",
    "active_weeks": [
      11,
      18,
      28
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-O",
    "num": "O",
    "prio": "MEDIO",
    "actividad": "SISTEMA GUIADO VEHICULAR",
    "ubicacion": "",
    "frecuencia": "",
    "presupuesto_proyectado": 15000,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-1",
    "num": 1,
    "prio": "ALTO",
    "actividad": "Mantenimiento preventivo de guiado vehicular Edificio estacionamiento",
    "ubicacion": "CLUB",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 11800,
    "responsable": "WILIAM ANTICONA",
    "fecha_tdr_revision": "46172",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "APROBADO\nACTA N°005-26",
    "proveedor": "PARKING SOLUTIONS SAC",
    "monto_sin_igv": 0,
    "estado_original": "EN COORDINACIÓN PARA SU EJECUCIÓN",
    "active_weeks": [
      12,
      13,
      28
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-P",
    "num": "P",
    "prio": "MEDIO",
    "actividad": "TABLEROS ELECTRICOS",
    "ubicacion": "",
    "frecuencia": "",
    "presupuesto_proyectado": 19000,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-1",
    "num": 1,
    "prio": "ALTO",
    "actividad": "Mantenimiento de 277 tableros electricos",
    "ubicacion": "CLUB",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 10000,
    "responsable": "MARLON RIVERA",
    "fecha_tdr_revision": "46171",
    "fecha_tdr_envio": "46175",
    "rq": "480704112",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "EN LOGISTICA, PARA PROGRAMAR LAS VISITAS DE CAMPO.",
    "active_weeks": [
      15,
      27,
      39
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-2",
    "num": 2,
    "prio": "ALTO",
    "actividad": "Actualizacion de diagramas de 277 tableros electricos",
    "ubicacion": "CLUB",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 9000,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [
      15,
      27,
      39
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-Q",
    "num": "Q",
    "prio": "MEDIO",
    "actividad": "MANTENIMIENTO EXTINTORES",
    "ubicacion": "",
    "frecuencia": "",
    "presupuesto_proyectado": 20000,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-1",
    "num": 1,
    "prio": "ALTO",
    "actividad": "Mantenimiento de 303 Extintores y 12 de backup",
    "ubicacion": "CLUB",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 20000,
    "responsable": "LEOMAR HUARACA",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "46129",
    "rq": "480702942",
    "acuerdo": "APROBADO\nACTA N°006-26",
    "proveedor": "EXTINTORES TEVI SAC",
    "monto_sin_igv": 38065.94,
    "estado_original": "EN PROCESO DE CONTRATO",
    "active_weeks": [
      15
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-R",
    "num": "R",
    "prio": "MEDIO",
    "actividad": "MANTENIMIENTO SISTEMA ACI",
    "ubicacion": "",
    "frecuencia": "",
    "presupuesto_proyectado": 0,
    "responsable": "",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "",
    "rq": "",
    "acuerdo": "",
    "proveedor": "",
    "monto_sin_igv": 0,
    "estado_original": "",
    "active_weeks": [],
    "assigned_staff_id": null,
    "status": "Pendiente"
  },
  {
    "id": "pm-1",
    "num": 1,
    "prio": "ALTO",
    "actividad": "Mantenimiento de del sistema ACI",
    "ubicacion": "CLUB",
    "frecuencia": "ANUAL",
    "presupuesto_proyectado": 0,
    "responsable": "LEOMAR HUARACA",
    "fecha_tdr_revision": "",
    "fecha_tdr_envio": "46137",
    "rq": "480703119",
    "acuerdo": "APROBADO\nACTA N°005-26",
    "proveedor": "BAMETSA SAC",
    "monto_sin_igv": 14142.77,
    "estado_original": "EN PROCESO DE CONTRATO",
    "active_weeks": [
      24
    ],
    "assigned_staff_id": null,
    "status": "Pendiente"
  }
];
